import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import * as tinyRoot from "../dist/index.js";
import { TinyChuOpenCodePlugin } from "../dist/opencode/plugin.js";
import { TinyChuOpenCodeTuiPlugin } from "../dist/opencode/tui-plugin.js";

const EXPECTED_INSTALL_MODES = ["offline-bundle", "internal-registry", "developer-file"];
const EXPECTED_ROOT_EXPORT_NAMES = [
  "ANALYSIS_WORKFLOW_PHASE_IDS",
  "ARTIFACT_CONTRACTS",
  "ARTIFACT_TYPES",
  "DEFAULT_SMALL_CONTEXT_MODELS",
  "POWERSHELL_OPENCODE_RUNTIME",
  "POWERSHELL_TOOLING_PROFILE",
  "PublicDispatcher",
  "QWEN_PUBLIC_LIMITS",
  "SAFE_TOOLING_LIMITS",
  "TaskStore",
  "TinyChuModeDispatchError",
  "TinyChuOpenCodePlugin",
  "TinyChuOpenCodeTuiPlugin",
  "TinyChuRuntimeModeError",
  "WikiBundler",
  "WorkflowStore",
  "acquireSafeToolingLock",
  "aggregateButtonTraces",
  "aggregationDriftCheck",
  "appendJsonLine",
  "appendNamingProposalEvent",
  "appendWikiErrorBookRecord",
  "atomicMarkdownWrite",
  "boundedText",
  "buildContextPacket",
  "buildNamingIndex",
  "buttonWorkerResultCheck",
  "buttonWorkflowDoneClaim",
  "callMcpToolFromRegistry",
  "checkArtifactMarkdown",
  "checkDocsConsistency",
  "checkMermaidMarkdown",
  "checkNamingDictionary",
  "createAnalysisWorkflowDefinition",
  "createAnalysisWorkflowStart",
  "createApiBackendTrace",
  "createApiContractCatalog",
  "createArtifactFormatTemplate",
  "createArtifactPackManifest",
  "createArtifactPublishApply",
  "createArtifactPublishManifest",
  "createArtifactWorkspaceCommit",
  "createArtifactWorkspacePrepare",
  "createAuthPermissionTrace",
  "createBusinessLogicMap",
  "createButtonWorkerPacket",
  "createButtonWorkflowPlan",
  "createChunkedWritePlan",
  "createClaimEvidenceCheck",
  "createCodeContextScan",
  "createContextBudgetSimulation",
  "createContextDigest",
  "createDashboardSnapshot",
  "createDefaultAgentModelTemplates",
  "createDefaultSmallContextRunGate",
  "createDoctor",
  "createDtoSchemaMap",
  "createEnvironmentDoctor",
  "createErrorTransactionMap",
  "createEvidenceGate",
  "createEvidenceQa",
  "createEvidenceSnapshot",
  "createGitWeeklyReport",
  "createIncrementalEvidenceCache",
  "createIntegrationCatalog",
  "createJsonPatchPreview",
  "createJsonYamlTransformPreview",
  "createLegacyRepoIndex",
  "createNamingContext",
  "createOrchestrationHealth",
  "createPlanReviewGate",
  "createPowerShellCommandGuard",
  "createPowerShellToolchainProbe",
  "createProviderEndpointPreflight",
  "createPublicJobResumePacket",
  "createQwenRetryPolicy",
  "createReduxStateFlowMap",
  "createRepoMap",
  "createResumePacket",
  "createRunDiagnostics",
  "createSafePatchApply",
  "createSafePatchCheck",
  "createSessionPreflight",
  "createSmallContextOrchestrationProfile",
  "createSmallContextRunGate",
  "createSmallModelContributionEvaluation",
  "createSmallModelReplay",
  "createStructuralRewritePreview",
  "createStructuralSearchAst",
  "createTestImpactPlanner",
  "createTinyChuInstallCheck",
  "createTinyChuPlugin",
  "createToolCallConformanceProbe",
  "createToolUsagePlan",
  "createTraceDiagramRender",
  "createTraceabilityMatrix",
  "createUiActionTrace",
  "createUiLayoutCatalog",
  "createUxRationaleTrace",
  "createUxReverseReport",
  "createUxValidationMatrix",
  "createWikiErrorBookRecord",
  "createWorkerPacketOptimizer",
  "createWorkflow",
  "createWorkflowAudit",
  "createWorkflowCheckpoint",
  "createWorkflowClose",
  "createWorkflowDefinition",
  "createWorkflowDefinitionNodes",
  "createWorkflowNextPacket",
  "createWorkflowPacketFitCheck",
  "createWorkflowProgressHeartbeat",
  "createWorkflowResumePacket",
  "createWorkflowSotAudit",
  "createWorkflowStatus",
  "dispatchButtonWorkflow",
  "dispatchMcpJsonRpc",
  "dispatchMcpJsonRpcLine",
  "ensureDir",
  "extractDocumentedToolMentions",
  "extractNamingSymbols",
  "fixMermaidMarkdown",
  "hashSourceTarget",
  "isPathInsideRoot",
  "isWorkerRuntimeMode",
  "listMcpToolsFromRegistry",
  "loadContextBundle",
  "loadNamingDictionary",
  "markdownEnvelopeCheck",
  "mcpDescriptorForToolSpec",
  "normalizeMermaidMarkdown",
  "normalizeSafeRelativePath",
  "normalizeTinyChuRuntimeMode",
  "parseNamingDictionary",
  "parsePlanMarkdown",
  "proposeWikiDocumentsFromRepoMap",
  "readJsonFile",
  "readJsonLines",
  "readPlanStatus",
  "readWikiErrorBookRecords",
  "readWorkspaceFile",
  "recommendModelOptionControls",
  "rejectRejectedPlanReviewGate",
  "removeIfExists",
  "renderBudgetedOutput",
  "renderCompactPowerShellToolingGuide",
  "renderCompactSmallContextGuide",
  "renderPowerShellToolingGuide",
  "renderProjectSnapshotSummary",
  "renderSmallContextGuide",
  "reportLayoutTruth",
  "resolvePathInsideRoot",
  "resolveTinyChuPaths",
  "schemaFingerprintForToolSpec",
  "selectPlanFocus",
  "startMcpStdioLoop",
  "updateLayoutTruth",
  "uxSourceFingerprint",
  "validateAgentModelTemplate",
  "verifyLayoutTruth",
  "writeJsonAtomic",
  "writeLoopGuard",
  "writeNamingIndex",
  "writePlanTemplate",
  "writeProjectSnapshot",
  "writeRulesSnapshot",
  "writeTextAtomic",
];

test("root module keeps the public ABI stable", async () => {
  const packageJson = JSON.parse(await readFile("package.json", "utf8"));

  assert.equal(packageJson.exports["."], "./dist/index.js");
  assert.equal(packageJson.exports["./opencode"], "./dist/opencode/plugin.js");
  assert.equal(packageJson.exports["./tui"], "./dist/opencode/tui-plugin.js");
  assert.equal(typeof tinyRoot.createTinyChuPlugin, "function");
  assert.equal(typeof tinyRoot.createGitWeeklyReport, "function");
  assert.equal(tinyRoot.TinyChuOpenCodePlugin, TinyChuOpenCodePlugin);
  assert.equal(tinyRoot.TinyChuOpenCodeTuiPlugin, TinyChuOpenCodeTuiPlugin);
  assert.equal(tinyRoot.POWERSHELL_OPENCODE_RUNTIME.shell.executable, "pwsh");
  const directInstall = tinyRoot.createTinyChuInstallCheck();
  assert.equal(directInstall.requiredTools.length, 99);
  assert.equal(directInstall.runtimeMode, "orchestrator_worker");
  assert.equal(directInstall.packageName, "tiny-chu");
  assert.equal(directInstall.opencodeEntrypoint, "./dist/opencode/plugin.js");
  assert.equal(directInstall.opencodeTuiEntrypoint, "./dist/opencode/tui-plugin.js");
  assert.equal(directInstall.status, "ready");
  assert.equal(directInstall.installDocs, "INSTALL.md");
  assert.equal(directInstall.opencodeShim, "templates/opencode/plugins/tiny-chu.ts");
  assert.equal(directInstall.opencodeTuiConfig, "templates/opencode/tui.json");
  assert.equal(directInstall.opencodeTuiShim, "templates/opencode/plugins/tiny-chu-tui.ts");
  assert.equal(directInstall.offlineBundleName, "tiny-chu-offline-vX.Y.Z.tar.gz");
  assert.deepEqual(directInstall.installModes, EXPECTED_INSTALL_MODES);
  assert.deepEqual(Object.keys(tinyRoot).sort(), EXPECTED_ROOT_EXPORT_NAMES);
});
